-- Create table for news/articles
create table public.news (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  content text,
  category text not null default 'Pengumuman',
  image text,
  alt text,
  date text not null,
  published_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_featured boolean default false
);

-- Enable Row Level Security
alter table public.news enable row level security;

-- Allow public read access
create policy "Public can view news"
  on public.news
  for select
  to anon
  using (true);

-- Allow authenticated users to insert (optional, for CMS later)
create policy "Authenticated users can insert news"
  on public.news
  for insert
  to authenticated
  with check (true);

-- Seed sample data
insert into public.news (title, excerpt, category, image, alt, date, is_featured)
values
  (
    'Implementasi Kurikulum Metaverse di Laboratorium Digital',
    'SMPN 1 Hitech resmi meluncurkan modul pembelajaran berbasis Virtual Reality untuk mata pelajaran Fisika dan Sejarah.',
    'Inovasi',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDQ2lA6fwKOsPHFuBwFroVfFGzQdape3GQGQtOhzh7PFBZPm-B5507Me6XST7Y3ipJPFnMoF1AWEBOh2oLiKqXLi_jHSXQE1vjrX6D5Ngj8arZW3Bvyz3Lz9fxGJH4VPfp4Ixr7cKPQM6oW2K_eMQGrDwAgvORUjUPAKOHf7HeNZZY7WYLJamlrnsvUWgWYoJ5BwWP0ceZhLkwpJX9i3FywFG_Xiz3bqB88BYxjxvoHt5JOxnw05adROYc4b-Uqt9wzGkANSs9dTOM',
    'A clean, high-tech classroom at SMPN 1 Hitech featuring advanced digital whiteboards and students using sleek laptops.',
    '15 OKT 2024',
    false
  ),
  (
    'Hitech Olympic 2024: Integrasi Esports dan Atletik',
    'Pekan olahraga tahunan sekolah kali ini menghadirkan kompetisi teknologi pendukung performa atlet siswa.',
    'Kegiatan',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuAYw5syuXVptANTXt-BG67t0TBo5dt_Ic8nlqS8dmEgsn3A68tjA2twJPHwYL2JT6YDMIYuzkS1TpaqzS1wFQViWbp0pQ3poKQJT5VhgUPPiaV5thcIZMkzCepxw2jATJ820q0Bf-RpU8Ypmq2Qt-InbhCSn-hLK_ItCBgpF0vgf8LRanfphmAdGV1ZiDQ1VDdtySRsCbLgnCC1mnkIIofYYI2AniaskeA_GgEPYERZoe1UnlYHb4m8PTMDEqou89SXD4VZCV4DbTA',
    'A wide shot of a prestigious award ceremony in a modern school auditorium.',
    '12 OKT 2024',
    false
  ),
  (
    'Jadwal Seleksi PPDB Jalur Prestasi Teknologi',
    'Penerimaan siswa baru jalur khusus talenta digital akan segera dibuka melalui portal resmi sekolah.',
    'Pengumuman',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDLaGnCipTMetlUpTYiwQf9vq4Mwjeq_6AruWVUms7tKv_nClYhv6qqvGcjG1O7bnzDFQli8A25YqQoX2JisdgO6NG2Ksb7G7ki5rnuonDYXmIwJfR8QNiKFdJezYwbMd9bklB3WqGRadtrJBjU6F9O9eupGRtp0osNFwSfrV_I_0CdnCLyaKOqP6NE531UWPLoRVRvrnVTKbUOL_81juBv_Vd-S0spn1zA5lFKyX2512U_Ec5aYwdY3YDYV6i6b7TX9OtzKsPmpyQ',
    'A professional close-up of a student speaking at a digital podium during a school announcement.',
    '10 OKT 2024',
    false
  ),
  (
    'Smart Garden: Proyek Ekologi Berbasis IoT Siswa Kelas 9',
    'Siswa berhasil mengintegrasikan sensor kelembaban tanah dengan sistem penyiraman otomatis tenaga surya.',
    'Inovasi',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDNNB598Ue7CmOcdr9AR1SEMVBuHSyjDgsE2dy6lu7tBqNcNYhQ55NWuEfsxQiTyWULEBbUbuDbR5e3TXCqrJEz3yos184WdpqxolqYU998eY3r8W5S4HLdJLl8fVQMWV5CQzGigDyxTxBNxwnfnIRRQwtQe5ksGZNeO-jsYH-rJ6j87udVDYZuz-1y9dFfL96U0g-EAAZXnM-7jnx52x3zF-M0xJRxjY-8hLEBNU8V1Ix_K_OLVelBqfbCCvOM5GBgFmkzw36cfFk',
    'An artistic shot of a green school garden integrated with hydroponic systems and smart sensors.',
    '08 OKT 2024',
    false
  ),
  (
    'Medali Emas Olimpiade Sains Nasional Bidang Informatika',
    'Dua siswa SMPN 1 Hitech meraih prestasi tertinggi dalam kompetisi pemrograman tingkat nasional.',
    'Prestasi',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDWb0enYapKKrO_lYePs_v8-EipbSXyTm7W7sPlJE5SnzWdO8q1tBsJMKS1zPSY72HMKUYRsBADfRjsWWp3ZFGT1CQZ8bkpU5MZVzOkBcMjsCCEwvikxYtiDDW0B88ujEby2PgPYgUOG47Pj0UfC5FVMYAyD9TApwQmH2xAdcovRQd3Yr_ox1_cOHhWBJDMvhE0umYJJz-Ge8PueAxXeGwwWmegLvnxJpiaXU-g83MwYPPacgWubT-g4Z042Mx4n68mLPsBGHx4gXY',
    'A wide shot of a prestigious award ceremony in a modern school auditorium.',
    '05 OKT 2024',
    false
  ),
  (
    'Workshop Literasi Digital: Etika Berinternet untuk Gen-Alpha',
    'Program pembekalan bagi siswa untuk menjadi warga digital yang bijak dan bertanggung jawab.',
    'Kegiatan',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuDhJKSW8Mkm-akDeGm5mUeglsgYg7depwRb77Y9Jyi8FPymAWoeCFhuVHHVDD1K2D_kBAkvYRgNoHXg676dzLz3sKn41038_L_uv6C5pz1fwnv3Sne8fPElpGtOVs5ud_Buz6aRiP2sp6KtymSyvu93Qr2EoCw54Oy_c0k6-CtAxogvbDQSzOyLWduYrDeUEGoAQK7M6mXaLNGhODqPAuamg7myxcfZlK8TMx-S0citP_cXZvceJhN_d3jgwONpcFEs3z-gGEmR2kU',
    'A classroom where students are engaged in a collaborative workshop, working with tablet devices and physical prototype models.',
    '02 OKT 2024',
    false
  );
