module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#424754',
        'error': '#ffb4ab',
        'surface-container-low': '#131b2e',
        'tertiary-container': '#ca8100',
        'secondary': '#4cd7f6',
        'on-tertiary-fixed-variant': '#653e00',
        'outline': '#8c909f',
        'on-secondary-fixed-variant': '#004e5c',
        'inverse-on-surface': '#283044',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-container': '#00424e',
        'primary-fixed': '#d8e2ff',
        'primary-container': '#4d8eff',
        'on-secondary': '#003640',
        'on-background': '#dae2fd',
        'surface-container-highest': '#2d3449',
        'inverse-surface': '#dae2fd',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#4cd7f6',
        'on-secondary-fixed': '#001f26',
        'tertiary': '#ffb95f',
        'on-tertiary-container': '#3e2400',
        'background': '#0b1326',
        'surface-tint': '#adc6ff',
        'surface-container-high': '#222a3d',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#002e6a',
        'surface-dim': '#0b1326',
        'on-primary-fixed': '#001a42',
        'on-surface-variant': '#c2c6d6',
        'secondary-container': '#03b5d3',
        'on-error': '#690005',
        'on-surface': '#dae2fd',
        'surface-variant': '#2d3449',
        'secondary-fixed': '#acedff',
        'surface-container-lowest': '#060e20',
        'on-tertiary': '#472a00',
        'surface-bright': '#31394d',
        'tertiary-fixed-dim': '#ffb95f',
        'on-primary-container': '#00285d',
        'tertiary-fixed': '#ffddb8',
        'on-error-container': '#ffdad6',
        'surface-container': '#171f33',
        'inverse-primary': '#005ac2',
        'surface': '#0b1326',
        'on-tertiary-fixed': '#2a1700',
        primary: '#adc6ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'stack-lg': '64px',
        'gutter': '24px',
        'stack-md': '32px',
        'margin-page': '40px',
        base: '8px',
        'stack-sm': '16px',
      },
      fontFamily: {
        'label-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'title-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '1.0', fontWeight: '500' }],
        'display-lg': ['56px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'title-lg': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '700' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
